batch:
  BatchJobDefinition: 'job_run:1'
  BatchJobName: 'test'
  BatchJobQueue: 'test'

train:
  train_url: '815969174475.dkr.ecr.us-east-1.amazonaws.com/sm-tf-nightly-gpu:latest'
  data_path: "s3://sfn-sagemaker-workflow/data"
  hyper_parameter:
    batch_size: 64
    epoch: 1