FROM python:3.8.10-slim-buster

WORKDIR /app
COPY . /app

RUN apt update && \
apt install --no-install-recommends -y build-essential gcc curl ca-certificates python3 && \
apt clean && rm -rf /var/lib/apt/lists/*
RUN pip uninstall torch torchvision -y && pip install --no-cache-dir -U torch==1.9.1 torchvision==0.10.1 pycocotools==2.0.2 

CMD ["python","./main.py"]
